image: registry.gitlab.com/pages/hugo:latest
test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo --config config.toml -d public/
  artifacts:
    paths:
    - public
  only:
  - master