image: registry.gitlab.com/pages/hugo:latest
test:
  script:
  - hugo
  except:
  - master

before_script:
  - echo 'SDAFSADFSDAF SDAFDSAF' > r.txt

after_script:
  - cat r.txt

pages:
  script:
  - hugo --config config.toml -d public/
  artifacts:
    paths:
    - public
  only:
  - master